---
abstract: 'Programmatically query the perlapi'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-APIReference
no_index:
  directory:
    - t
    - inc
requires:
  Class::XSAccessor: '1.05'
  Data::Dumper: '0'
  Sereal::Decoder: '3.005'
  Sereal::Encoder: '3.005'
  parent: '0'
version: '0.21'
